### ISSUE TITLE
More verbose Usage Instructions

### ISSUE THREAD

**Issue by Ruthalas** [xbmc/notrobro#30]
After digging through the current issues, I found links to the following:
[Project Summary](https://docs.google.com/document/d/1AXIyxK6p3m_IQBWOgBDXxaUFi_457pSblPUQti9uEpo/edit)
[How to use the detection script](https://github.com/xbmc/notrobro/tree/master/notrobro-detector#notrobro-detector)

I feel like I have an understanding what this tool is intended to do, how it is structurally put together, and sufficient information to run the detector. 

But how do I use the results in Kodi?
Is some part of this repo a plugin that will correctly parse the output of the dectector?

I'd appreciate some guidance on putting all the pieces together- this is a very cool project.

**Comment by razzeee** [comment]
Hey, thanks for stopping by :)

To use this with kodi, just zip this folder up https://github.com/xbmc/notrobro/tree/master/service.notrobro and you should be able to install that in kodi. Fair warning, the implementation is pretty basic, but should work, if you have the needed `.edl` files.

**Comment by Ruthalas** [comment]
Thank you!
