### ISSUE TITLE
Use upnext addon for the outro skip

### ISSUE THREAD

**Issue by Dnkhatri** [xbmc/notrobro#32]
We already have a plugin that allows us to go to the next episode instead of a separate addon adding the ability to read the outro time to the upnext plugin would be a better option.
https://github.com/im85288/service.upnext/issues/171

**Comment by Hitcher** [comment]
I'd prefer if UpNext checked if this was running and used the outtro to trigger its popup.

**Comment by razzeee** [comment]
As there is currently no action that we need to take, I'm going to close this.
Feel free to reopen, when it has been implemented in upnext.
