### ISSUE TITLE
Add automatic addon check

### ISSUE THREAD

**Issue by Razzeee** [xbmc/notrobro#9]
We should use travis to run automatic error detection from our addon check project https://github.com/xbmc/addon-check

**Comment by LordGameleo** [comment]
@Razzeee I would like to work on this issue, is it open?

**Comment by Razzeee** [comment]
Sure, feel free to do.

You can find a reference implementation here https://github.com/jdf76/plugin.video.youtube

**Comment by LordGameleo** [comment]
@Razzeee can you please explain it a bit?

**Comment by LordGameleo** [comment]
@Razzeee can you please explain it a bit? Should I touch .travis.yml and make changes such that it will also do addon-check using kodi-addon-checker $TRAVIS_BUILD_DIR --branch=<name-of-branch>

**Comment by Razzeee** [comment]
yes, that's what i would expect

**Comment by LordGameleo** [comment]
how can we know which branch it is for?

**Comment by Rechi** [comment]
As https://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions tells new submissions are currently only accepted for Leia. So use `--branch=leia`.

**Comment by LordGameleo** [comment]
@Rechi it can vary later on?

**Comment by Rechi** [comment]
After the next major Kodi version release (v19 M*) only submissions for that version will be allowed.
But for now Leia is fine.

**Comment by LordGameleo** [comment]
Okay I will use that branch :+1

**Comment by LordGameleo** [comment]
@Razzeee Please close this issue
